[2024-10-16T18:16:48.748+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T18:16:48.771+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-16T18:16:48.787+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T18:16:48.794+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-16T18:16:48.797+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [queued]> from DB
[2024-10-16T18:16:48.818+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-16T18:16:48.823+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T18:16:48.823+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-16T18:16:48.830+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-16T18:16:48.830+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [queued]>
[2024-10-16T18:16:48.831+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-16T18:16:48.832+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T18:16:48.836+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-16T18:16:48.841+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-16T18:16:48.842+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [queued]>
[2024-10-16T18:16:48.842+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-10-16T18:16:48.854+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): generate_dbt_docs> on 2024-10-16 18:16:14.702384+00:00
[2024-10-16T18:16:48.858+0000] {standard_task_runner.py:57} INFO - Started process 1388 to run task
[2024-10-16T18:16:48.861+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'generate_dbt_docs', 'manual__2024-10-16T18:16:14.702384+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models.py', '--cfg-path', '/tmp/tmpmeg52ofu']
[2024-10-16T18:16:48.862+0000] {standard_task_runner.py:85} INFO - Job 86: Subtask generate_dbt_docs
[2024-10-16T18:16:48.862+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7ca9505550>]
[2024-10-16T18:16:48.920+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T18:16:48.929+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [running]> on host 888d2c584607
[2024-10-16T18:16:48.930+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 1388)
[2024-10-16T18:16:48.930+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 1388)
[2024-10-16T18:16:48.931+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-16T18:16:48.933+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [running]> from DB
[2024-10-16T18:16:48.980+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T18:16:48.990+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-16T18:16:49.029+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-16T18:16:49.045+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='generate_dbt_docs' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T18:16:14.702384+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-16T18:16:14.702384+00:00'
[2024-10-16T18:16:49.046+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-16T18:16:49.046+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-16T18:16:49.047+0000] {bash.py:186} DEBUG - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='generate_dbt_docs' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T18:16:14.702384+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-16T18:16:14.702384+00:00'
[2024-10-16T18:16:49.047+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-16T18:16:49.048+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt docs generate --profiles-dir /opt/airflow/dbt --project-dir /opt/airflow/dbt']
[2024-10-16T18:16:49.057+0000] {subprocess.py:86} INFO - Output:
[2024-10-16T18:16:51.237+0000] {subprocess.py:93} INFO - [0m18:16:51  Running with dbt=1.8.7
[2024-10-16T18:16:51.541+0000] {subprocess.py:93} INFO - [0m18:16:51  Registered adapter: ***=1.8.2
[2024-10-16T18:16:51.750+0000] {subprocess.py:93} INFO - [0m18:16:51  Unable to do partial parsing because config vars, config profile, or config target have changed
[2024-10-16T18:16:51.752+0000] {subprocess.py:93} INFO - [0m18:16:51  Unable to do partial parsing because profile has changed
[2024-10-16T18:16:53.901+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [running]> from DB
[2024-10-16T18:16:53.915+0000] {job.py:213} DEBUG - [heartbeat]
[2024-10-16T18:16:53.980+0000] {subprocess.py:93} INFO - [0m18:16:53  [[33mWARNING[0m]: Deprecated functionality
[2024-10-16T18:16:53.981+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-10-16T18:16:53.981+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-10-16T18:16:53.981+0000] {subprocess.py:93} INFO - information.
[2024-10-16T18:16:54.415+0000] {subprocess.py:93} INFO - [0m18:16:54  Found 2 models, 18 data tests, 1 source, 540 macros
[2024-10-16T18:16:54.418+0000] {subprocess.py:93} INFO - [0m18:16:54
[2024-10-16T18:16:54.518+0000] {subprocess.py:93} INFO - [0m18:16:54  Concurrency: 4 threads (target='dev')
[2024-10-16T18:16:54.519+0000] {subprocess.py:93} INFO - [0m18:16:54
[2024-10-16T18:16:55.020+0000] {subprocess.py:93} INFO - [0m18:16:55  Building catalog
[2024-10-16T18:16:55.192+0000] {subprocess.py:93} INFO - [0m18:16:55  Catalog written to /opt/airflow/dbt/target/catalog.json
[2024-10-16T18:16:55.911+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-16T18:16:55.940+0000] {__init__.py:75} DEBUG - Lineage called with inlets: [], outlets: []
[2024-10-16T18:16:55.941+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:16:14.702384+00:00 [running]> from DB
[2024-10-16T18:16:55.956+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-16T18:16:55.957+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=run_dbt_models, task_id=generate_dbt_docs, execution_date=20241016T181614, start_date=20241016T181648, end_date=20241016T181655
[2024-10-16T18:16:55.957+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 7.126288
[2024-10-16T18:16:55.973+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-16T18:16:55.980+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-10-16T18:16:56.036+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_models @ 2024-10-16 18:16:14.702384+00:00: manual__2024-10-16T18:16:14.702384+00:00, state:running, queued_at: 2024-10-16 18:16:14.718067+00:00. externally triggered: True>: 0 task(s)
[2024-10-16T18:16:56.036+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
