[2024-10-15T23:14:24.952+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:14:24.977+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-15T23:14:24.993+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:14:25.002+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-15T23:14:25.004+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [queued]> from DB
[2024-10-15T23:14:25.033+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:14:25.046+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-15T23:14:25.046+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-15T23:14:25.047+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:14:25.047+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [queued]>
[2024-10-15T23:14:25.049+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:14:25.055+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-15T23:14:25.060+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-15T23:14:25.061+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:14:25.061+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [queued]>
[2024-10-15T23:14:25.062+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-10-15T23:14:25.075+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): test.dbt_btc_transform.stg_kaggle__btcusdt> on 2024-10-15 23:09:07.210288+00:00
[2024-10-15T23:14:25.079+0000] {standard_task_runner.py:57} INFO - Started process 945 to run task
[2024-10-15T23:14:25.083+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'test.dbt_btc_transform.stg_kaggle__btcusdt', 'manual__2024-10-15T23:09:07.210288+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models.py', '--cfg-path', '/tmp/tmpfp79bstf']
[2024-10-15T23:14:25.084+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask test.dbt_btc_transform.stg_kaggle__btcusdt
[2024-10-15T23:14:25.085+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7b0c199c10>]
[2024-10-15T23:14:25.144+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:14:25.153+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [running]> on host d867809303f2
[2024-10-15T23:14:25.154+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 945)
[2024-10-15T23:14:25.154+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 945)
[2024-10-15T23:14:25.155+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-15T23:14:25.157+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [running]> from DB
[2024-10-15T23:14:25.205+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:14:25.215+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-15T23:14:25.251+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-15T23:14:25.268+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='test.dbt_btc_transform.stg_kaggle__btcusdt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:09:07.210288+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:09:07.210288+00:00'
[2024-10-15T23:14:25.269+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-15T23:14:25.269+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-15T23:14:25.270+0000] {bash.py:186} DEBUG - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='test.dbt_btc_transform.stg_kaggle__btcusdt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:09:07.210288+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:09:07.210288+00:00'
[2024-10-15T23:14:25.270+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-15T23:14:25.271+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            export DBT_SCHEMA=analytics &&\n            cd /opt/airflow/dbt &&\n            /home/airflow/.local/bin/dbt --no-write-json test --target dev --models stg_kaggle__btcusdt\n            ']
[2024-10-15T23:14:25.280+0000] {subprocess.py:86} INFO - Output:
[2024-10-15T23:14:27.628+0000] {subprocess.py:93} INFO - [0m23:14:27  Running with dbt=1.8.7
[2024-10-15T23:14:27.944+0000] {subprocess.py:93} INFO - [0m23:14:27  Registered adapter: ***=1.8.2
[2024-10-15T23:14:28.287+0000] {subprocess.py:93} INFO - [0m23:14:28  Found 1 model, 1 source, 540 macros
[2024-10-15T23:14:28.290+0000] {subprocess.py:93} INFO - [0m23:14:28
[2024-10-15T23:14:28.291+0000] {subprocess.py:93} INFO - [0m23:14:28  Nothing to do. Try checking your model configs and model specification args
[2024-10-15T23:14:28.945+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-15T23:14:28.977+0000] {__init__.py:75} DEBUG - Lineage called with inlets: [], outlets: []
[2024-10-15T23:14:28.977+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:09:07.210288+00:00 [running]> from DB
[2024-10-15T23:14:28.996+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-15T23:14:28.997+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=run_dbt_models, task_id=test.dbt_btc_transform.stg_kaggle__btcusdt, execution_date=20241015T230907, start_date=20241015T231425, end_date=20241015T231428
[2024-10-15T23:14:28.998+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 3.949617
[2024-10-15T23:14:29.017+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-15T23:14:29.025+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-10-15T23:14:29.089+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_models @ 2024-10-15 23:09:07.210288+00:00: manual__2024-10-15T23:09:07.210288+00:00, state:running, queued_at: 2024-10-15 23:09:07.224159+00:00. externally triggered: True>: 3 task(s)
[2024-10-15T23:14:29.090+0000] {dagrun.py:718} DEBUG - number of scheduleable tasks for <DagRun run_dbt_models @ 2024-10-15 23:09:07.210288+00:00: manual__2024-10-15T23:09:07.210288+00:00, state:running, queued_at: 2024-10-15 23:09:07.224159+00:00. externally triggered: True>: 1 task(s)
[2024-10-15T23:14:29.092+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:09:07.210288+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:14:29.093+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:09:07.210288+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:14:29.093+0000] {taskinstance.py:1103} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:09:07.210288+00:00 [None]>
[2024-10-15T23:14:29.097+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
