[2024-10-16T18:07:48.660+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T18:07:48.687+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-16T18:07:48.707+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T18:07:48.715+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-16T18:07:48.718+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [queued]> from DB
[2024-10-16T18:07:48.741+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-16T18:07:48.747+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T18:07:48.748+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-16T18:07:48.760+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-16T18:07:48.760+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [queued]>
[2024-10-16T18:07:48.761+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-16T18:07:48.763+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T18:07:48.769+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-16T18:07:48.774+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-16T18:07:48.775+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [queued]>
[2024-10-16T18:07:48.775+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-10-16T18:07:48.789+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): model.dbt_btc_transform.int_hourly_trades> on 2024-10-16 18:06:30.304200+00:00
[2024-10-16T18:07:48.793+0000] {standard_task_runner.py:57} INFO - Started process 1050 to run task
[2024-10-16T18:07:48.797+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'model.dbt_btc_transform.int_hourly_trades', 'manual__2024-10-16T18:06:30.304200+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models.py', '--cfg-path', '/tmp/tmp5x0yhzbm']
[2024-10-16T18:07:48.798+0000] {standard_task_runner.py:85} INFO - Job 70: Subtask model.dbt_btc_transform.int_hourly_trades
[2024-10-16T18:07:48.799+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7ca9505550>]
[2024-10-16T18:07:48.857+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T18:07:48.866+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [running]> on host 888d2c584607
[2024-10-16T18:07:48.867+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 1050)
[2024-10-16T18:07:48.867+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 1050)
[2024-10-16T18:07:48.868+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-16T18:07:48.870+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [running]> from DB
[2024-10-16T18:07:48.916+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T18:07:48.924+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-16T18:07:48.961+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-16T18:07:48.977+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='model.dbt_btc_transform.int_hourly_trades' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T18:06:30.304200+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-16T18:06:30.304200+00:00'
[2024-10-16T18:07:48.977+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-16T18:07:48.978+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-16T18:07:48.979+0000] {bash.py:186} DEBUG - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='model.dbt_btc_transform.int_hourly_trades' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T18:06:30.304200+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-16T18:06:30.304200+00:00'
[2024-10-16T18:07:48.979+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-16T18:07:48.980+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            export DBT_SCHEMA=analytics &&\n            cd /opt/airflow/dbt &&\n            /home/airflow/.local/bin/dbt --no-write-json run --target dev --models int_hourly_trades\n            ']
[2024-10-16T18:07:48.988+0000] {subprocess.py:86} INFO - Output:
[2024-10-16T18:07:51.532+0000] {subprocess.py:93} INFO - [0m18:07:51  Running with dbt=1.8.7
[2024-10-16T18:07:51.835+0000] {subprocess.py:93} INFO - [0m18:07:51  Registered adapter: ***=1.8.2
[2024-10-16T18:07:52.221+0000] {subprocess.py:93} INFO - [0m18:07:52  Found 2 models, 18 data tests, 1 source, 540 macros
[2024-10-16T18:07:52.224+0000] {subprocess.py:93} INFO - [0m18:07:52
[2024-10-16T18:07:52.421+0000] {subprocess.py:93} INFO - [0m18:07:52  Concurrency: 4 threads (target='dev')
[2024-10-16T18:07:52.422+0000] {subprocess.py:93} INFO - [0m18:07:52
[2024-10-16T18:07:52.432+0000] {subprocess.py:93} INFO - [0m18:07:52  1 of 1 START sql table model analytics.int_hourly_trades ....................... [RUN]
[2024-10-16T18:07:52.538+0000] {subprocess.py:93} INFO - [0m18:07:52  1 of 1 ERROR creating sql table model analytics.int_hourly_trades .............. [[31mERROR[0m in 0.10s]
[2024-10-16T18:07:52.558+0000] {subprocess.py:93} INFO - [0m18:07:52
[2024-10-16T18:07:52.558+0000] {subprocess.py:93} INFO - [0m18:07:52  Finished running 1 table model in 0 hours 0 minutes and 0.33 seconds (0.33s).
[2024-10-16T18:07:52.561+0000] {subprocess.py:93} INFO - [0m18:07:52
[2024-10-16T18:07:52.561+0000] {subprocess.py:93} INFO - [0m18:07:52  [31mCompleted with 1 error and 0 warnings:[0m
[2024-10-16T18:07:52.563+0000] {subprocess.py:93} INFO - [0m18:07:52
[2024-10-16T18:07:52.564+0000] {subprocess.py:93} INFO - [0m18:07:52    Database Error in model int_hourly_trades (models/marts/intermediate/int_hourly_trades.sql)
[2024-10-16T18:07:52.564+0000] {subprocess.py:93} INFO -   column "close_price" does not exist
[2024-10-16T18:07:52.564+0000] {subprocess.py:93} INFO -   LINE 41:         (close_price - open_price) * 1.0 / open_price as per...
[2024-10-16T18:07:52.564+0000] {subprocess.py:93} INFO -                     ^
[2024-10-16T18:07:52.565+0000] {subprocess.py:93} INFO -   HINT:  Perhaps you meant to reference the column "source.close_time".
[2024-10-16T18:07:52.565+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_btc_transform/models/marts/intermediate/int_hourly_trades.sql
[2024-10-16T18:07:52.565+0000] {subprocess.py:93} INFO - [0m18:07:52
[2024-10-16T18:07:52.565+0000] {subprocess.py:93} INFO - [0m18:07:52  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-10-16T18:07:53.393+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-16T18:07:53.394+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [running]> from DB
[2024-10-16T18:07:53.414+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-16T18:07:53.415+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [running]> from DB
[2024-10-16T18:07:53.418+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 4.65707
[2024-10-16T18:07:53.421+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-16T18:07:53.421+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=run_dbt_models, task_id=model.dbt_btc_transform.int_hourly_trades, execution_date=20241016T180630, start_date=20241016T180748, end_date=20241016T180753
[2024-10-16T18:07:53.438+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-16T18:07:53.438+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 70 for task model.dbt_btc_transform.int_hourly_trades (Bash command failed. The command returned a non-zero exit code 1.; 1050)
[2024-10-16T18:07:53.446+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-16T18:07:53.507+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_models @ 2024-10-16 18:06:30.304200+00:00: manual__2024-10-16T18:06:30.304200+00:00, state:running, queued_at: 2024-10-16 18:06:30.664597+00:00. externally triggered: True>: 6 task(s)
[2024-10-16T18:07:53.508+0000] {dagrun.py:718} DEBUG - number of scheduleable tasks for <DagRun run_dbt_models @ 2024-10-16 18:06:30.304200+00:00: manual__2024-10-16T18:06:30.304200+00:00, state:running, queued_at: 2024-10-16 18:06:30.664597+00:00. externally triggered: True>: 4 task(s)
[2024-10-16T18:07:53.512+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:06:30.304200+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T18:07:53.513+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:06:30.304200+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-16T18:07:53.513+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:06:30.304200+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 3 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1), upstream_task_ids={'test.dbt_btc_transform.int_hourly_trades', 'model.dbt_btc_transform.stg_kaggle__btcusdt', 'model.dbt_btc_transform.int_hourly_trades', 'test.dbt_btc_transform.stg_kaggle__btcusdt'}
[2024-10-16T18:07:53.514+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T18:06:30.304200+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 3 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1), upstream_task_ids={'test.dbt_btc_transform.int_hourly_trades', 'model.dbt_btc_transform.stg_kaggle__btcusdt', 'model.dbt_btc_transform.int_hourly_trades', 'test.dbt_btc_transform.stg_kaggle__btcusdt'}
[2024-10-16T18:07:53.516+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-16T18:06:30.304200+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T18:07:53.517+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-16T18:06:30.304200+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2024-10-16T18:07:53.517213+00:00 and task will be retried at 2024-10-16T18:11:51.731239+00:00.
[2024-10-16T18:07:53.517+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-16T18:06:30.304200+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-10-16T18:07:53.517213+00:00 and task will be retried at 2024-10-16T18:11:51.731239+00:00.
[2024-10-16T18:07:53.522+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T18:07:53.523+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-16T18:07:53.525+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.dbt_btc_transform.int_hourly_trades', 'wait_for_dbt_init'}
[2024-10-16T18:07:53.526+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.test.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.dbt_btc_transform.int_hourly_trades', 'wait_for_dbt_init'}
[2024-10-16T18:07:53.527+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T18:07:53.528+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2024-10-16T18:07:53.528472+00:00 and task will be retried at 2024-10-16T18:12:53.418395+00:00.
[2024-10-16T18:07:53.529+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.model.dbt_btc_transform.int_hourly_trades manual__2024-10-16T18:06:30.304200+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-10-16T18:07:53.528472+00:00 and task will be retried at 2024-10-16T18:12:53.418395+00:00.
[2024-10-16T18:07:53.537+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
