[2024-10-15T23:07:22.914+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:07:22.935+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-15T23:07:22.950+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:07:22.957+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-15T23:07:22.959+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> from DB
[2024-10-15T23:07:22.984+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:07:22.995+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-15T23:07:22.995+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-15T23:07:22.995+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:07:22.996+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]>
[2024-10-15T23:07:22.997+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:07:23.003+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-15T23:07:23.007+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-15T23:07:23.007+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:07:23.008+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]>
[2024-10-15T23:07:23.008+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-10-15T23:07:23.020+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): model.dbt_btc_transform.stg_kaggle__btcusdt> on 2024-10-15 23:07:20.618561+00:00
[2024-10-15T23:07:23.024+0000] {standard_task_runner.py:57} INFO - Started process 642 to run task
[2024-10-15T23:07:23.028+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'model.dbt_btc_transform.stg_kaggle__btcusdt', 'manual__2024-10-15T23:07:20.618561+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models.py', '--cfg-path', '/tmp/tmplo6yaoqa']
[2024-10-15T23:07:23.028+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask model.dbt_btc_transform.stg_kaggle__btcusdt
[2024-10-15T23:07:23.029+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7b0c199c10>]
[2024-10-15T23:07:23.086+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:07:23.094+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [running]> on host d867809303f2
[2024-10-15T23:07:23.095+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 642)
[2024-10-15T23:07:23.095+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 642)
[2024-10-15T23:07:23.096+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-15T23:07:23.097+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [running]> from DB
[2024-10-15T23:07:23.141+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:07:23.149+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-15T23:07:23.182+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-15T23:07:23.197+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='model.dbt_btc_transform.stg_kaggle__btcusdt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:07:20.618561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:07:20.618561+00:00'
[2024-10-15T23:07:23.197+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-15T23:07:23.198+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-15T23:07:23.198+0000] {bash.py:186} DEBUG - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='model.dbt_btc_transform.stg_kaggle__btcusdt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:07:20.618561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:07:20.618561+00:00'
[2024-10-15T23:07:23.199+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-15T23:07:23.199+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            export DBT_SCHEMA=analytics &&\n            cd /opt/airflow/dbt &&\n            /home/airflow/.local/bin/dbt --no-write-json run --target dev --models stg_kaggle__btcusdt\n            ']
[2024-10-15T23:07:23.207+0000] {subprocess.py:86} INFO - Output:
[2024-10-15T23:07:25.342+0000] {subprocess.py:93} INFO - [0m23:07:25  Running with dbt=1.8.7
[2024-10-15T23:07:25.640+0000] {subprocess.py:93} INFO - [0m23:07:25  Registered adapter: ***=1.8.2
[2024-10-15T23:07:26.294+0000] {subprocess.py:93} INFO - [0m23:07:26  Encountered an error:
[2024-10-15T23:07:26.295+0000] {subprocess.py:93} INFO - Compilation Error
[2024-10-15T23:07:26.295+0000] {subprocess.py:93} INFO -   Model 'model.dbt_btc_transform.stg_kaggle__btcusdt' (models/staging/kaggle/stg_kaggle__btcusdt.sql) depends on a source named 'raw.bitcoin_trades' which was not found
[2024-10-15T23:07:26.924+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-10-15T23:07:26.925+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [running]> from DB
[2024-10-15T23:07:26.944+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-10-15T23:07:26.945+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [running]> from DB
[2024-10-15T23:07:26.947+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 3.950951
[2024-10-15T23:07:26.950+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-15T23:07:26.950+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=run_dbt_models, task_id=model.dbt_btc_transform.stg_kaggle__btcusdt, execution_date=20241015T230720, start_date=20241015T230722, end_date=20241015T230726
[2024-10-15T23:07:26.966+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-15T23:07:26.966+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task model.dbt_btc_transform.stg_kaggle__btcusdt (Bash command failed. The command returned a non-zero exit code 2.; 642)
[2024-10-15T23:07:26.981+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-15T23:07:27.040+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_models @ 2024-10-15 23:07:20.618561+00:00: manual__2024-10-15T23:07:20.618561+00:00, state:running, queued_at: 2024-10-15 23:07:20.626118+00:00. externally triggered: True>: 4 task(s)
[2024-10-15T23:07:27.041+0000] {dagrun.py:718} DEBUG - number of scheduleable tasks for <DagRun run_dbt_models @ 2024-10-15 23:07:20.618561+00:00: manual__2024-10-15T23:07:20.618561+00:00, state:running, queued_at: 2024-10-15 23:07:20.626118+00:00. externally triggered: True>: 3 task(s)
[2024-10-15T23:07:27.043+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:07:27.046+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2024-10-15T23:07:27.046465+00:00 and task will be retried at 2024-10-15T23:12:26.947544+00:00.
[2024-10-15T23:07:27.046+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-10-15T23:07:27.046465+00:00 and task will be retried at 2024-10-15T23:12:26.947544+00:00.
[2024-10-15T23:07:27.048+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:07:20.618561+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:07:27.049+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:07:20.618561+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'test.dbt_btc_transform.stg_kaggle__btcusdt'}
[2024-10-15T23:07:27.049+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:07:20.618561+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'test.dbt_btc_transform.stg_kaggle__btcusdt'}
[2024-10-15T23:07:27.049+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:07:20.618561+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:07:27.051+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:07:27.053+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'wait_for_dbt_init'}
[2024-10-15T23:07:27.053+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'wait_for_dbt_init'}
[2024-10-15T23:07:27.053+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:07:27.058+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
