[2024-10-18T19:07:29.959+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-18T19:07:29.989+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-18T19:07:30.009+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-18T19:07:30.017+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-18T19:07:30.019+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [queued]> from DB
[2024-10-18T19:07:30.049+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-18T19:07:30.050+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-10-18T19:07:30.050+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-18T19:07:30.050+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-18T19:07:30.051+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [queued]>
[2024-10-18T19:07:30.053+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-10-18T19:07:30.054+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-18T19:07:30.060+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-18T19:07:30.062+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-18T19:07:30.063+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [queued]>
[2024-10-18T19:07:30.063+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-10-18T19:07:30.078+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): delete_btcusdt> on 2024-10-18 19:07:25.569120+00:00
[2024-10-18T19:07:30.083+0000] {standard_task_runner.py:57} INFO - Started process 286 to run task
[2024-10-18T19:07:30.087+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'btcusdt_data_ingestion', 'delete_btcusdt', 'manual__2024-10-18T19:07:25.569120+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/ingest_btcusdt_data.py', '--cfg-path', '/tmp/tmp0m43jkc4']
[2024-10-18T19:07:30.091+0000] {standard_task_runner.py:85} INFO - Job 164: Subtask delete_btcusdt
[2024-10-18T19:07:30.091+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7fb8145ae550>]
[2024-10-18T19:07:30.154+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-18T19:07:30.182+0000] {task_command.py:410} INFO - Running <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [running]> on host cd6dcf6990b1
[2024-10-18T19:07:30.183+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 286)
[2024-10-18T19:07:30.185+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 286)
[2024-10-18T19:07:30.185+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-18T19:07:30.188+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [running]> from DB
[2024-10-18T19:07:30.237+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-18T19:07:30.247+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-18T19:07:30.282+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-18T19:07:30.299+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='btcusdt_data_ingestion' AIRFLOW_CTX_TASK_ID='delete_btcusdt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T19:07:25.569120+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-18T19:07:25.569120+00:00'
[2024-10-18T19:07:30.299+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-18T19:07:30.300+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-18T19:07:30.308+0000] {base.py:73} INFO - Using connection ID 'company_dw' for task execution.
[2024-10-18T19:07:30.785+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-10-18T19:07:30.786+0000] {__init__.py:75} DEBUG - Lineage called with inlets: [], outlets: []
[2024-10-18T19:07:30.786+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: btcusdt_data_ingestion.delete_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [running]> from DB
[2024-10-18T19:07:30.807+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-18T19:07:30.808+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=btcusdt_data_ingestion, task_id=delete_btcusdt, execution_date=20241018T190725, start_date=20241018T190730, end_date=20241018T190730
[2024-10-18T19:07:30.808+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 0.75635
[2024-10-18T19:07:31.034+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-18T19:07:31.088+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-10-18T19:07:31.124+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun btcusdt_data_ingestion @ 2024-10-18 19:07:25.569120+00:00: manual__2024-10-18T19:07:25.569120+00:00, state:running, queued_at: 2024-10-18 19:07:25.603395+00:00. externally triggered: True>: 3 task(s)
[2024-10-18T19:07:31.125+0000] {dagrun.py:718} DEBUG - number of scheduleable tasks for <DagRun btcusdt_data_ingestion @ 2024-10-18 19:07:25.569120+00:00: manual__2024-10-18T19:07:25.569120+00:00, state:running, queued_at: 2024-10-18 19:07:25.603395+00:00. externally triggered: True>: 1 task(s)
[2024-10-18T19:07:31.125+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: btcusdt_data_ingestion.ingest_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-10-18T19:07:31.126+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: btcusdt_data_ingestion.ingest_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'split_btcusdt'}
[2024-10-18T19:07:31.126+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: btcusdt_data_ingestion.ingest_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'split_btcusdt'}
[2024-10-18T19:07:31.127+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: btcusdt_data_ingestion.ingest_btcusdt manual__2024-10-18T19:07:25.569120+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-18T19:07:31.132+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
