[2024-10-15T23:03:37.924+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:03:37.954+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-15T23:03:37.971+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:03:37.980+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-15T23:03:37.983+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> from DB
[2024-10-15T23:03:38.004+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-15T23:03:38.005+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Ready To Reschedule' PASSED: True, Task is not in reschedule mode.
[2024-10-15T23:03:38.005+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-15T23:03:38.006+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:03:38.011+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:03:38.017+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-10-15T23:03:38.017+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]>
[2024-10-15T23:03:38.018+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Ready To Reschedule' PASSED: True, Task is not in reschedule mode.
[2024-10-15T23:03:38.018+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-15T23:03:38.021+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:03:38.022+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:03:38.024+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-10-15T23:03:38.029+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-15T23:03:38.030+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [queued]>
[2024-10-15T23:03:38.030+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-10-15T23:03:38.044+0000] {taskinstance.py:1327} INFO - Executing <Task(ExternalTaskWithinDaysSensor): wait_for_dbt_init> on 2024-10-15 23:03:31.498100+00:00
[2024-10-15T23:03:38.047+0000] {standard_task_runner.py:57} INFO - Started process 560 to run task
[2024-10-15T23:03:38.050+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'wait_for_dbt_init', 'manual__2024-10-15T23:03:31.498100+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models.py', '--cfg-path', '/tmp/tmpfm7hr_dg']
[2024-10-15T23:03:38.051+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask wait_for_dbt_init
[2024-10-15T23:03:38.052+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7b0c199c10>]
[2024-10-15T23:03:38.109+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:03:38.117+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [running]> on host d867809303f2
[2024-10-15T23:03:38.118+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 560)
[2024-10-15T23:03:38.118+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 560)
[2024-10-15T23:03:38.119+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-15T23:03:38.121+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [running]> from DB
[2024-10-15T23:03:38.164+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:03:38.173+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-15T23:03:38.207+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-15T23:03:38.222+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='wait_for_dbt_init' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:03:31.498100+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:03:31.498100+00:00'
[2024-10-15T23:03:38.222+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-15T23:03:38.223+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-15T23:03:38.234+0000] {base.py:255} INFO - Success criteria met. Exiting.
[2024-10-15T23:03:38.235+0000] {__init__.py:75} DEBUG - Lineage called with inlets: [], outlets: []
[2024-10-15T23:03:38.235+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.wait_for_dbt_init manual__2024-10-15T23:03:31.498100+00:00 [running]> from DB
[2024-10-15T23:03:38.246+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-15T23:03:38.247+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=run_dbt_models, task_id=wait_for_dbt_init, execution_date=20241015T230331, start_date=20241015T230338, end_date=20241015T230338
[2024-10-15T23:03:38.247+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 0.229259
[2024-10-15T23:03:38.260+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-15T23:03:38.272+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-10-15T23:03:38.332+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_models @ 2024-10-15 23:03:31.498100+00:00: manual__2024-10-15T23:03:31.498100+00:00, state:running, queued_at: 2024-10-15 23:03:31.510882+00:00. externally triggered: True>: 2 task(s)
[2024-10-15T23:03:38.333+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
