[2024-10-16T19:23:59.750+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T19:23:59.774+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-16T19:23:59.806+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T19:23:59.817+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-16T19:23:59.821+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [queued]> from DB
[2024-10-16T19:23:59.842+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-16T19:23:59.848+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T19:23:59.848+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-16T19:23:59.855+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-16T19:23:59.857+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [queued]>
[2024-10-16T19:23:59.857+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-16T19:23:59.860+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T19:23:59.866+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-16T19:23:59.871+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-16T19:23:59.871+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [queued]>
[2024-10-16T19:23:59.872+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-10-16T19:23:59.884+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): generate_dbt_docs> on 2024-10-16 19:18:21.052800+00:00
[2024-10-16T19:23:59.887+0000] {standard_task_runner.py:57} INFO - Started process 2723 to run task
[2024-10-16T19:23:59.890+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'generate_dbt_docs', 'manual__2024-10-16T19:18:21.052800+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models.py', '--cfg-path', '/tmp/tmpbtyawlh9']
[2024-10-16T19:23:59.891+0000] {standard_task_runner.py:85} INFO - Job 111: Subtask generate_dbt_docs
[2024-10-16T19:23:59.892+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7ca9505550>]
[2024-10-16T19:23:59.946+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T19:23:59.954+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [running]> on host 888d2c584607
[2024-10-16T19:23:59.955+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 2723)
[2024-10-16T19:23:59.956+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 2723)
[2024-10-16T19:23:59.956+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-16T19:23:59.958+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [running]> from DB
[2024-10-16T19:24:00.002+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T19:24:00.011+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-16T19:24:00.045+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-16T19:24:00.060+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='generate_dbt_docs' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T19:18:21.052800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-16T19:18:21.052800+00:00'
[2024-10-16T19:24:00.060+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-16T19:24:00.061+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-16T19:24:00.061+0000] {bash.py:186} DEBUG - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='generate_dbt_docs' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T19:18:21.052800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-16T19:18:21.052800+00:00'
[2024-10-16T19:24:00.062+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-16T19:24:00.062+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt docs generate --profiles-dir /opt/airflow/dbt --project-dir /opt/airflow/dbt']
[2024-10-16T19:24:00.070+0000] {subprocess.py:86} INFO - Output:
[2024-10-16T19:24:02.320+0000] {subprocess.py:93} INFO - [0m19:24:02  Running with dbt=1.8.7
[2024-10-16T19:24:02.612+0000] {subprocess.py:93} INFO - [0m19:24:02  Registered adapter: ***=1.8.2
[2024-10-16T19:24:02.829+0000] {subprocess.py:93} INFO - [0m19:24:02  Unable to do partial parsing because config vars, config profile, or config target have changed
[2024-10-16T19:24:02.831+0000] {subprocess.py:93} INFO - [0m19:24:02  Unable to do partial parsing because profile has changed
[2024-10-16T19:24:04.923+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [running]> from DB
[2024-10-16T19:24:04.937+0000] {job.py:213} DEBUG - [heartbeat]
[2024-10-16T19:24:04.969+0000] {subprocess.py:93} INFO - [0m19:24:04  [[33mWARNING[0m]: Deprecated functionality
[2024-10-16T19:24:04.969+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-10-16T19:24:04.969+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-10-16T19:24:04.969+0000] {subprocess.py:93} INFO - information.
[2024-10-16T19:24:05.602+0000] {subprocess.py:93} INFO - [0m19:24:05  Found 2 models, 25 data tests, 1 source, 540 macros
[2024-10-16T19:24:05.616+0000] {subprocess.py:93} INFO - [0m19:24:05
[2024-10-16T19:24:05.821+0000] {subprocess.py:93} INFO - [0m19:24:05  Concurrency: 4 threads (target='dev')
[2024-10-16T19:24:05.822+0000] {subprocess.py:93} INFO - [0m19:24:05
[2024-10-16T19:24:06.726+0000] {subprocess.py:93} INFO - [0m19:24:06  Building catalog
[2024-10-16T19:24:06.936+0000] {subprocess.py:93} INFO - [0m19:24:06  Catalog written to /opt/airflow/dbt/target/catalog.json
[2024-10-16T19:24:07.625+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-16T19:24:07.657+0000] {__init__.py:75} DEBUG - Lineage called with inlets: [], outlets: []
[2024-10-16T19:24:07.657+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T19:18:21.052800+00:00 [running]> from DB
[2024-10-16T19:24:07.673+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-16T19:24:07.673+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=run_dbt_models, task_id=generate_dbt_docs, execution_date=20241016T191821, start_date=20241016T192359, end_date=20241016T192407
[2024-10-16T19:24:07.674+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 7.816114
[2024-10-16T19:24:07.691+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-16T19:24:07.707+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-10-16T19:24:07.765+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_models @ 2024-10-16 19:18:21.052800+00:00: manual__2024-10-16T19:18:21.052800+00:00, state:running, queued_at: 2024-10-16 19:18:21.063070+00:00. externally triggered: True>: 0 task(s)
[2024-10-16T19:24:07.765+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
