[2024-10-16T16:13:20.708+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T16:13:20.731+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-16T16:13:20.745+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T16:13:20.752+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-16T16:13:20.755+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [queued]> from DB
[2024-10-16T16:13:20.776+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-16T16:13:20.781+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T16:13:20.781+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-16T16:13:20.787+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-16T16:13:20.788+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [queued]>
[2024-10-16T16:13:20.788+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-16T16:13:20.790+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-16T16:13:20.794+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-16T16:13:20.799+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-16T16:13:20.799+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [queued]>
[2024-10-16T16:13:20.799+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-10-16T16:13:20.813+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): generate_dbt_docs> on 2024-10-16 16:13:01.431647+00:00
[2024-10-16T16:13:20.816+0000] {standard_task_runner.py:57} INFO - Started process 222 to run task
[2024-10-16T16:13:20.820+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'generate_dbt_docs', 'manual__2024-10-16T16:13:01.431647+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models.py', '--cfg-path', '/tmp/tmpebwvap1y']
[2024-10-16T16:13:20.820+0000] {standard_task_runner.py:85} INFO - Job 59: Subtask generate_dbt_docs
[2024-10-16T16:13:20.821+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7ca9505550>]
[2024-10-16T16:13:20.875+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T16:13:20.884+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [running]> on host 888d2c584607
[2024-10-16T16:13:20.884+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 222)
[2024-10-16T16:13:20.885+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 222)
[2024-10-16T16:13:20.886+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-16T16:13:20.887+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [running]> from DB
[2024-10-16T16:13:20.932+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-16T16:13:20.943+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-16T16:13:20.982+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-16T16:13:21.000+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='generate_dbt_docs' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T16:13:01.431647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-16T16:13:01.431647+00:00'
[2024-10-16T16:13:21.001+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-16T16:13:21.001+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-16T16:13:21.002+0000] {bash.py:186} DEBUG - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='generate_dbt_docs' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T16:13:01.431647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-16T16:13:01.431647+00:00'
[2024-10-16T16:13:21.003+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-16T16:13:21.004+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt docs generate --profiles-dir /opt/airflow/dbt --project-dir /opt/airflow/dbt']
[2024-10-16T16:13:21.046+0000] {subprocess.py:86} INFO - Output:
[2024-10-16T16:13:23.977+0000] {subprocess.py:93} INFO - [0m16:13:23  Running with dbt=1.8.7
[2024-10-16T16:13:24.286+0000] {subprocess.py:93} INFO - [0m16:13:24  Registered adapter: ***=1.8.2
[2024-10-16T16:13:24.465+0000] {subprocess.py:93} INFO - [0m16:13:24  Unable to do partial parsing because config vars, config profile, or config target have changed
[2024-10-16T16:13:24.467+0000] {subprocess.py:93} INFO - [0m16:13:24  Unable to do partial parsing because profile has changed
[2024-10-16T16:13:25.861+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [running]> from DB
[2024-10-16T16:13:25.875+0000] {job.py:213} DEBUG - [heartbeat]
[2024-10-16T16:13:26.700+0000] {subprocess.py:93} INFO - [0m16:13:26  Found 1 model, 1 source, 540 macros
[2024-10-16T16:13:26.703+0000] {subprocess.py:93} INFO - [0m16:13:26
[2024-10-16T16:13:26.862+0000] {subprocess.py:93} INFO - [0m16:13:26  Concurrency: 4 threads (target='dev')
[2024-10-16T16:13:26.863+0000] {subprocess.py:93} INFO - [0m16:13:26
[2024-10-16T16:13:27.101+0000] {subprocess.py:93} INFO - [0m16:13:27  Building catalog
[2024-10-16T16:13:27.230+0000] {subprocess.py:93} INFO - [0m16:13:27  Catalog written to /opt/airflow/dbt/target/catalog.json
[2024-10-16T16:13:27.913+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-16T16:13:27.943+0000] {__init__.py:75} DEBUG - Lineage called with inlets: [], outlets: []
[2024-10-16T16:13:27.943+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-16T16:13:01.431647+00:00 [running]> from DB
[2024-10-16T16:13:27.960+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-16T16:13:27.961+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=run_dbt_models, task_id=generate_dbt_docs, execution_date=20241016T161301, start_date=20241016T161320, end_date=20241016T161327
[2024-10-16T16:13:27.961+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 7.172355
[2024-10-16T16:13:27.978+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-16T16:13:28.023+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-10-16T16:13:28.079+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_models @ 2024-10-16 16:13:01.431647+00:00: manual__2024-10-16T16:13:01.431647+00:00, state:running, queued_at: 2024-10-16 16:13:01.953177+00:00. externally triggered: True>: 0 task(s)
[2024-10-16T16:13:28.080+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
